server:
  port: 8081

spring:
  data:
    mongodb:
      database: dms
      host: localhost
      port: 27017

app:
  config:
    workspace:
      base-uri: /api/workspace
      api:
        delete-workspace-by-id: /delete/{id}
        update-workspace: /update



jwt:
  secret: oWxiA4J+s34cHVbcwhYIcN5P0xq9CjYAkUz/ai3Wh8Q=

